name: Check commit titles

on:
  pull_request:

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # The logic below handles the npm publication:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Check commit titles
      run: |
        curl ${{ github.event.pull_request.commits_url }} > commits.txt
        jq --version
        cat commits.txt | jq -r '.[].commit.message' | tee titles.txt

        cat titles.txt | grep -vE '(chore|feat|fix|refactor)(\(\S+\))?!?: [a-z]+' || \
            (
                echo "Please check your commit titles, they should correspond to https://www.conventionalcommits.org/en/v1.0.0/";
                false
            )

        cat titles.txt | grep -vE '(feat|fix)(\(\S+\))?!?: [a-z]+' || \
        (
            echo "You have to provice at least one 'feat'|'fix' commit to publish new version of changed packages.";
            echo "If you don't want to release new version then just ignore the check.";
            false
        )

