name: "[manual]: Docker tag"

on:
  workflow_dispatch:
    inputs:
      stag:
        description: "ytsaurus/ui-nightly:[SOURCE_TAG]"
        required: true
      ttag:
        description: "ytsaurus/ui:[TARGET_TAG]"
        required: true

jobs:
  docker-tag:
    runs-on: ubuntu-latest
    steps:
      - name: "Docker tag"
        run: |
          echo '${{ secrets.DOCKER_HUB_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_HUB_LOGIN}} --password-stdin

          SOURCE_IMAGE=ytsaurus/ui-nightly:${{ inputs.stag }}
          TARGET_IMAMGE=ytsaurus/ui:${{ inputs.ttag }}

          docker pull ${SOURCE_IMAGE}
          docker tag ${SOURCE_IMAGE} ${TARGET_IMAMGE}
          docker push ${TARGET_IMAMGE}
