name: "[manual]: Docker tag"

on:
  workflow_dispatch:
    inputs:
      stag:
        description: "ytsaurus/ui-nightly:[SOURCE_TAG]"
        required: true
      ttag:
        description: "ytsaurus/ui:[TARGET_TAG]"
        required: true

jobs:
  docker-tag:
    runs-on: ubuntu-latest
    steps:
      - name: "Docker tag"
        run: |
          SOURCE_IMAGE=ghcr.io/ytsaurus/ui-nightly:${{ inputs.stag }}
          TARGET_IMAMGE=ghcr.io/ytsaurus/ui:${{ inputs.ttag }}

          docker pull ${SOURCE_IMAGE}
          docker tag ${SOURCE_IMAGE} ${TARGET_IMAMGE}

          echo '${{ secrets.GITHUB_TOKEN }}' | docker login --username ${{ github.actor }} --password-stdin ghcr.io
          docker push ${TARGET_IMAMGE}
